version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-04-07T05-28-58Z
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - minio-data:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=miniopasswordplaceholder
      # Do NOT use MINIO_DOMAIN or MINIO_SERVER_URL with Traefik.
      # All Routing is done by Traefik, just tell minio where to redirect to.
      - MINIO_BROWSER_REDIRECT_URL=https://minio.placeholderdomain.com
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      # Minio Storage EP
      - "traefik.http.routers.minio-storage.entrypoints=websecure"
      - "traefik.http.routers.minio-storage.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.minio-storage.rule=Host(`minio-storage.placeholderdomain.com`)"
      - "traefik.http.routers.minio-storage.service=minio-storage"
      - "traefik.http.services.minio-storage.loadbalancer.server.port=9000"
      # Minio Console EP
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.minio-console.rule=Host(`minio.placeholderdomain.com`)"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

volumes:
  minio-data:

networks:
  traefik-net:
    external: true
